#!/bin/bash

source_directory="/home/patrick/Desktop/githubportfolio/bash/ipblock/blockips.log"
backup_directory="/home/patrick/backups"

mkdir -p "$backup_directory"

# Timestamp
timestamp=$(date +"%Y%m%d%H%M%S")

# Get the back up file with the timestamp
backup_file="logs_backup_$timestamp.tar.gz"

# Archive the logfiles
tar -zcf "$backup_directory/$backup_file" "$source_directory"

# Confirm
if [ $? -eq 0 ]; then
    echo "Logs backup created successfully: $backup_directory/$backup_file"
else
    echo "Failed to create logs backup."
fi
